spring.application.name=backend-java
server.port=${PORT:8080}

spring.config.import=optional:file:.env[.properties]
OCI_PAR_URL=${OCI_PAR_URL:https://objectstorage.sa-bogota-1.oraclecloud.com/p/RDUhZAw0t_PRpLvch7JJ1N8U5YL-pi_-Wc8VeTxXZkNJdaGay_bwjMbzyjI9j92Z/n/axmccr00xq51/b/dato/o/}

spring.datasource.url=jdbc:h2:mem:communitydb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.h2.console.enabled=true
spring.docker.compose.enabled=${SPRING_DOCKER_COMPOSE_ENABLED:false}