-- V1 · Modelo inicial (análisis §5, tarea T01)
-- Flyway aplica este archivo una sola vez y lo anota en flyway_schema_history.
-- Nunca se edita después de aplicado: los cambios van en V2, V3, ...
--
-- Los valores en minúscula/camelCase (persona, botPropio, historial...) son los del contrato v1
-- (ingestion/discord/docs/CONTRACT.md §5) y se guardan tal cual llegan.
-- sentimiento, tema y estado_oci quedan sin CHECK hasta que la IA (fase 3) y OCI (fase 6) definan sus valores.

-- Cada lote que llega a la API (por lotes cada hora, o de a un mensaje desde el bot)
CREATE TABLE lotes_recibidos (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lote_id          text        NOT NULL UNIQUE,
    modo             text        NOT NULL CHECK (modo IN ('historial', 'tiempoReal')),
    version_contrato text        NOT NULL,
    recibido_en      timestamptz NOT NULL DEFAULT now(),
    total            integer     NOT NULL DEFAULT 0 CHECK (total >= 0),
    nuevos           integer     NOT NULL DEFAULT 0 CHECK (nuevos >= 0),
    actualizados     integer     NOT NULL DEFAULT 0 CHECK (actualizados >= 0),
    CHECK (nuevos + actualizados <= total)
);

-- Un mensaje de Discord = una fila (F1). La "etiqueta" son las columnas; la "caja" es contrato (jsonb)
CREATE TABLE mensajes (
    id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    discord_id           text        NOT NULL UNIQUE,
    canal_id             text        NOT NULL,
    autor_id             text        NOT NULL,
    autor_tipo           text        NOT NULL CHECK (autor_tipo IN ('persona', 'botPropio', 'otroBot')),
    autor_rol            text        NOT NULL CHECK (autor_rol IN ('miembro', 'mentor', 'staff')),
    es_simulado          boolean     NOT NULL DEFAULT false,
    fecha                timestamptz NOT NULL,
    responde_a           text,
    texto                text        NOT NULL DEFAULT '',   -- puede venir vacío (solo una imagen)
    contrato             jsonb       NOT NULL,              -- el mensaje completo del contrato v1
    version_contrato     text        NOT NULL,
    primera_vez_visto    timestamptz NOT NULL DEFAULT now(),
    actualizado_en       timestamptz NOT NULL DEFAULT now(),

    -- Etiquetas de la IA: el upsert nunca las pisa (F2)
    intencion            text CHECK (intencion IN ('TESTIMONIO', 'PREGUNTA_FAQ', 'COMENTARIO', 'OTRO')),
    confianza            double precision CHECK (confianza BETWEEN 0 AND 1),
    sentimiento          text,
    tema                 text,
    estado_clasificacion text NOT NULL DEFAULT 'PENDIENTE'
                         CHECK (estado_clasificacion IN ('PENDIENTE', 'OK', 'ERROR')),
    clasificado_en       timestamptz
);

-- Para el dashboard (N5): actividad por autor, por semana y por intención
CREATE INDEX idx_mensajes_autor_fecha ON mensajes (autor_id, fecha);
CREATE INDEX idx_mensajes_fecha       ON mensajes (fecha);
CREATE INDEX idx_mensajes_intencion   ON mensajes (intencion);

-- Lo que genera la IA y una persona aprueba o rechaza en el panel (N3, N6, N7)
CREATE TABLE borradores (
    id                        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mensaje_id                bigint REFERENCES mensajes (id),
    tipo                      text    NOT NULL
                              CHECK (tipo IN ('POST_LINKEDIN', 'CASO_EXITO', 'FAQ', 'RESPUESTA_BOT')),
    texto_ia                  text    NOT NULL,
    texto_final               text,
    estado                    text    NOT NULL DEFAULT 'PENDIENTE'
                              CHECK (estado IN ('PENDIENTE', 'APROBADO', 'RECHAZADO')),
    consentimiento_confirmado boolean NOT NULL DEFAULT false,
    aprobado_por              text,
    aprobado_en               timestamptz,
    tiempo_curaduria_seg      integer CHECK (tiempo_curaduria_seg >= 0),
    tokens_in                 integer CHECK (tokens_in >= 0),
    tokens_out                integer CHECK (tokens_out >= 0),
    estado_oci                text,
    ruta_oci                  text,
    creado_en                 timestamptz NOT NULL DEFAULT now(),
    -- Solo la FAQ semanal, que junta varias preguntas, puede no venir de un único mensaje
    CHECK (mensaje_id IS NOT NULL OR tipo = 'FAQ')
);

CREATE INDEX idx_borradores_estado     ON borradores (estado);
CREATE INDEX idx_borradores_mensaje_id ON borradores (mensaje_id);  -- PostgreSQL no indexa solo las claves foráneas
