-- V5 · FAQ semanal (tarea T06b, DEC-94 a DEC-99)
-- Una fila por semana: es la garantía de que nunca haya dos FAQ de la misma semana, aunque la tarea corra
-- muchas veces, se reinicie Java o haya dos Java a la vez. Registra también las semanas sin preguntas
-- repetidas (para no volver a intentarlas) y las que fallaron, con sus intentos.

CREATE TABLE faq_semanas (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Semana ISO de cuando corrió la tarea, en la zona horaria configurada (por ejemplo, 2026-W40)
    semana          text        NOT NULL UNIQUE,
    -- La ventana de dudas. Se fija en el primer intento: los reintentos usan la misma
    desde           timestamptz NOT NULL,
    hasta           timestamptz NOT NULL CHECK (hasta > desde),
    -- GENERADA: tiene su borrador FAQ. SIN_REPETIDAS: ninguna duda la repitieron 2 personas; no se reintenta.
    -- ERROR: falló el máximo de intentos. NULL: todavía no termina (falta, se está armando o se reintenta)
    estado          text CHECK (estado IN ('GENERADA', 'SIN_REPETIDAS', 'ERROR')),
    -- Lo que dijo la IA (cuántas repetidas y cuántas con respuesta, o por qué no hay FAQ) o el último error
    motivo          text,
    intentos        integer NOT NULL DEFAULT 0 CHECK (intentos >= 0),
    -- Números del último intento, sin textos (S11)
    dudas           integer CHECK (dudas >= 0),
    repetidas       integer CHECK (repetidas >= 0),
    con_respuesta   integer CHECK (con_respuesta >= 0 AND con_respuesta <= repetidas),
    -- El borrador FAQ (borradores.mensaje_id vacío, DEC-33). Solo en GENERADA
    borrador_id     bigint UNIQUE REFERENCES borradores (id),
    -- "Ocupada hasta": una ejecución la está armando. Si Java se cae, vence sola
    reservada_hasta timestamptz,
    creada_en       timestamptz NOT NULL DEFAULT now(),
    terminada_en    timestamptz,
    CHECK ((estado IS NOT DISTINCT FROM 'GENERADA') = (borrador_id IS NOT NULL))
);

-- Para juntar rápido las dudas de la ventana
CREATE INDEX idx_mensajes_dudas_por_fecha ON mensajes (fecha)
    WHERE intencion = 'PREGUNTA_FAQ' AND estado_clasificacion = 'OK';
