-- V8 · Subida de los borradores a OCI (tarea T09, DEC-127 a DEC-131)
-- Cada borrador tiene hasta DOS subidas al bucket, independientes: la de generados/ (cuando se crea) y la de
-- aprobados/ (cuando una persona lo aprueba). Una fila por borrador y carpeta: es la garantía de que nunca se
-- encole dos veces lo mismo, aunque la tarea corra muchas veces o haya dos Java a la vez.
-- La tarea en segundo plano crea las filas (PENDIENTE) y las sube; generar y aprobar no esperan a OCI.

CREATE TABLE subidas_oci (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    borrador_id     bigint      NOT NULL REFERENCES borradores (id),
    carpeta         text        NOT NULL CHECK (carpeta IN ('generados', 'aprobados')),
    -- PENDIENTE: falta subirlo o falló y se va a reintentar. SUBIDO: ya está en el bucket.
    -- ERROR: falló el máximo de intentos; no se reintenta solo (docs/OPERACION.md §12 explica cómo reintentarlo)
    estado          text        NOT NULL DEFAULT 'PENDIENTE' CHECK (estado IN ('PENDIENTE', 'SUBIDO', 'ERROR')),
    -- El nombre del objeto en el bucket (por ejemplo, aprobados/POST_LINKEDIN/2026-10-04/borrador-12.json).
    -- Nunca la URL PAR: es una credencial. Solo se llena cuando está SUBIDO
    ruta            text,
    intentos        integer     NOT NULL DEFAULT 0 CHECK (intentos >= 0),
    -- Por qué falló el último intento (sin la PAR ni textos: por ejemplo, "OCI respondió HTTP 500")
    ultimo_error    text,
    -- "Ocupada hasta": una ejecución la está subiendo, o está esperando para reintentar. Si Java se cae, vence sola
    reservada_hasta timestamptz,
    creada_en       timestamptz NOT NULL DEFAULT now(),
    subido_en       timestamptz,
    UNIQUE (borrador_id, carpeta),
    -- Solo lo SUBIDO tiene ruta y fecha de subida, y todo lo SUBIDO las tiene
    CHECK ((estado = 'SUBIDO') = (ruta IS NOT NULL)),
    CHECK ((estado = 'SUBIDO') = (subido_en IS NOT NULL))
);

-- Para tomar rápido lo que falta subir, del más antiguo al más nuevo
CREATE INDEX idx_subidas_oci_pendientes ON subidas_oci (id) WHERE estado = 'PENDIENTE';

-- Las columnas de V1 quedan sin uso: la subida se sigue en subidas_oci, porque cada borrador tiene dos
COMMENT ON COLUMN borradores.estado_oci IS 'Sin uso desde la V8: ver la tabla subidas_oci';
COMMENT ON COLUMN borradores.ruta_oci IS 'Sin uso desde la V8: ver la tabla subidas_oci';
